// Generated by 'promake functions' - do not edit by hand.
// Ambient types for Deno function handlers (req / env / ctx). Mirrors the
// customer-backend functions runtime contract. Regenerate with
// 'promake functions validate' or any 'promake functions create/update'.

/** The HTTP request passed to an http-triggered handler. */
interface FunctionRequest {
  method: string;
  url: string;
  headers: Record<string, string>;
  query: Record<string, string>;
  /** The parsed request body (JSON object, or raw text/null). */
  body: unknown;
  /** The real client IP resolved by the backend (X-Forwarded-For aware). */
  ip: string;
}

/**
 * A cron-triggered handler receives this instead of an HTTP request (so `req` is
 * a CronEvent when `ctx.trigger === "cron"`). Cron fires with ADMIN authority:
 * env.db/storage/emails are all admin and ctx.user is null.
 */
interface CronEvent {
  /** The cron expression that fired (e.g. "0 6 * * *"). */
  cron: string;
  /** The scheduled fire time, as an ISO string. */
  scheduledTime: string;
  /** The crons[].name that routed to this function. */
  name: string;
}

/** A minimal query options shape for env.db reads. */
interface DbQueryOptions {
  where?: Record<string, unknown>;
  limit?: number;
  offset?: number;
  orderBy?: string;
  populate?: string | string[];
  lang?: string;
}

/**
 * The data layer, scoped to the caller's permissions by the backend. This is
 * the dbcli ORM over a REST adapter (the frontend's exact data layer); the
 * generated @promakeai/orm types refine these signatures when pinned.
 */
interface FunctionDb {
  get(table: string, id: string | number, options?: DbQueryOptions): Promise<Record<string, unknown> | null>;
  list(table: string, options?: DbQueryOptions): Promise<Array<Record<string, unknown>>>;
  count(table: string, options?: DbQueryOptions): Promise<number>;
  create(table: string, data: Record<string, unknown>): Promise<Record<string, unknown>>;
  update(table: string, id: string | number, data: Record<string, unknown>): Promise<Record<string, unknown>>;
  delete(table: string, id: string | number): Promise<void>;
}

/**
 * A thin storage client (fetch wrapper over /storage/*), scoped to the caller's
 * token. It returns PRESIGNED URLS, not bytes: the Deno sandbox can only reach
 * the pod host, not S3, so byte transfer happens by fetching the returned URL
 * from a host that can. `isPublic` is a positional boolean (default false).
 *
 *   const up = await env.storage.uploadUrl("avatars/u1.png", "image/png", true);
 *   // up = { url, fields, key, cdnUrl } - POST the file (multipart, + "file") to up.url
 *   const down = await env.storage.downloadUrl("avatars/u1.png"); // { url }
 *   const { objects } = await env.storage.list("avatars/");       // [{ key, size, lastModified, url }]
 *   await env.storage.delete("avatars/u1.png");                   // { success }
 */
interface FunctionStorage {
  /** Presigned POST for an upload; `fields` go in the multipart body plus a "file" field. `cdnUrl` is the eventual public URL (meaningful for public uploads). */
  uploadUrl(key: string, contentType: string, isPublic?: boolean):
    Promise<{ url: string; fields: Record<string, string>; key: string; cdnUrl: string }>;
  /** Presigned, time-limited GET URL for an object. */
  downloadUrl(key: string, isPublic?: boolean): Promise<{ url: string }>;
  /** List objects under a prefix. `size` is bytes; `lastModified` is an ISO string. */
  list(prefix?: string): Promise<{ objects: Array<{ key: string; size: number; lastModified: string; url: string }> }>;
  /** Delete an object. */
  delete(key: string, isPublic?: boolean): Promise<{ success: boolean }>;
}

/**
 * Send a registered email template. ALWAYS sends with ADMIN authority (a function
 * is admin-authored), regardless of who invoked the function - a deliberate
 * asymmetry vs the caller-scoped env.db / env.storage. The admin token is closed
 * over by the runtime; /emails/send stays admin-gated for direct callers.
 *
 *   await env.emails.send("welcome", { to: "user@example.com", vars: { name: "Ada" } });
 *
 * Attachments: pass `attachments`. Each `content` may be a remote URL, a base64
 * string, or raw bytes (Uint8Array/ArrayBuffer) - the runtime handles encoding,
 * so you never base64 anything yourself. The simplest source is a stored file:
 *
 *   const url = await env.storage.downloadUrl("invoices/2026.pdf");
 *   await env.emails.send("welcome", { to, attachments: [{ filename: "invoice.pdf", content: url }] });
 *
 * Security: because send runs as admin, forwarding caller-controlled input
 * straight into `to`/`vars` (e.g. send(t, { to: req.body.email })) is an open
 * relay / spam vector. The author must validate / allow-list recipients first.
 */
interface FunctionEmailAttachment {
  /** Display name of the file (e.g. "invoice.pdf"). Determines the MIME type if contentType is omitted. */
  filename: string;
  /** A remote http(s) URL, a base64 string, or raw bytes. The runtime encodes bytes for you. */
  content: string | Uint8Array | ArrayBuffer;
  /** Optional MIME type; inferred from filename when omitted. */
  contentType?: string;
}

interface FunctionEmail {
  /** `template` is the flat slug (e.g. "welcome"); `vars` fill {{name}}/{{code}}/etc. Returns the send ack. */
  send(
    template: string,
    opts: { to: string; vars?: Record<string, string>; attachments?: FunctionEmailAttachment[] },
  ): Promise<{ sent: boolean; template: string; to: string }>;
}

/**
 * The environment handed to every handler. Exactly these three members; no token
 * is exposed (Object.keys(env) never contains one). Authority: `db` and `storage`
 * are caller-scoped (:own) on HTTP invokes; `emails` is ALWAYS admin. Under cron
 * all three are admin (cron fires as the admin principal).
 */
interface FunctionEnv {
  db: FunctionDb;
  storage: FunctionStorage;
  emails: FunctionEmail;
}

/**
 * A response builder you RETURN from an http handler (not a stateful writer); the
 * same builder is a no-op for cron, which has no HTTP response. Chainable.
 *
 *   return ctx.res.status(201).header("X-Trace", "abc").json({ created: true });
 */
interface FunctionResponse {
  /** JSON body; optional status (default 200). */
  json(data: unknown, status?: number): FunctionResponse;
  /** Text body; optional status (default 200) and contentType. */
  text(body: string, status?: number, contentType?: string): FunctionResponse;
  /** Set the status code. */
  status(code: number): FunctionResponse;
  /** Set a response header. */
  header(key: string, value: string): FunctionResponse;
  /** Redirect (default status 302). */
  redirect(url: string, status?: number): FunctionResponse;
}

/**
 * Per-invocation context. Branch on `trigger` to serve http and cron.
 *
 *   if (ctx.trigger === "http") return ctx.res.json({ user: ctx.user });
 *   ctx.waitUntil(env.db.create("audit", { at: Date.now() })); // non-blocking
 */
interface FunctionContext {
  /** "http" for a POST /functions/<name> invoke; "cron" for a scheduled fire. */
  trigger: "http" | "cron";
  /** The invoking principal, when the scoped token carries one (null for cron/anon). */
  user?: { id: string; role: string } | null;
  /** The tenant the invocation runs against. */
  tenantUuid?: string;
  /** Response builder (http); a no-op for cron. */
  res: FunctionResponse;
  /** Keep a deferred promise alive past the handler's return (best-effort; the process is short-lived). */
  waitUntil(p: Promise<unknown>): void;
}
