// Pure _redirects helpers: build the file, parse it back, match a request, and
// derive the routes a hydration harness should assert. No DOM, no IO, so they
// stay unit-testable; prerender.mjs and check-hydration.mjs import them.

/**
 * Build the Netlify-style `_redirects` body for the routes that were ACTUALLY
 * prerendered. Each real route resolves to its own directory index; everything
 * else (genuinely unknown paths, `:param` routes) falls back to the SPA shell.
 * Doubles as the SSG route manifest: the explicit list of prerendered routes a
 * host / edge router can read to decide directory-index vs shell.
 *
 * @param {string[]} routes routes with a written dist/<route>/index.html
 * @returns {string}
 */
export function buildRedirects(routes) {
  const lines = [
    "# Generated by prerender (SSG). Real prerendered routes resolve to their own",
    "# directory index; every other path falls back to the SPA shell (index.html).",
    "# Doubles as the SSG route manifest (the genuinely prerendered route list).",
  ];
  for (const route of routes) {
    const target = route === "/" ? "/index.html" : `${route.replace(/\/$/, "")}/index.html`;
    lines.push(`${route}  ${target}  200`);
  }
  // Catch-all LAST: Netlify matches top to bottom, so specific rules precede it.
  lines.push("/*  /index.html  200");
  return lines.join("\n") + "\n";
}

/**
 * Parse a `_redirects` body into ordered { from, to } rules, skipping blank and
 * `#` comment lines.
 *
 * @param {string} body
 * @returns {{ from: string, to: string }[]}
 */
export function parseRedirects(body) {
  const rules = [];
  for (const raw of String(body).split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const [from, to] = line.split(/\s+/);
    if (from && to) rules.push({ from, to });
  }
  return rules;
}

/**
 * Resolve a request path to its redirect target: the first exact `from` match,
 * else the `/*` catch-all. Returns the target path or null. (Existing-file-wins
 * is the host's job and is applied by the caller before this.)
 *
 * @param {string} reqPath
 * @param {{ from: string, to: string }[]} rules
 * @returns {string|null}
 */
export function matchRedirect(reqPath, rules) {
  // Strip any query string so an exact rule still matches `/about?x=1`,
  // symmetric with toServeRel's query handling on the direct-file path.
  const p = String(reqPath).split("?")[0];
  const rule = rules.find((r) => r.from === p) ?? rules.find((r) => r.from === "/*");
  return rule ? rule.to : null;
}

/**
 * Routes a hydration harness should assert: `/` plus every prerendered route
 * (every non-catch-all rule), deduped.
 *
 * @param {{ from: string, to: string }[]} rules
 * @returns {string[]}
 */
export function realRoutes(rules) {
  const out = ["/"];
  for (const r of rules) {
    if (r.from !== "/*" && r.from !== "/" && !out.includes(r.from)) out.push(r.from);
  }
  return out;
}

/**
 * Normalize a request/target path to a dist-relative path (no leading slash,
 * query stripped); "/" maps to index.html. Returns null on a `..` traversal
 * attempt so a caller never resolves outside the publish dir.
 *
 * @param {string} p
 * @returns {string|null}
 */
export function toServeRel(p) {
  let clean;
  try {
    clean = decodeURIComponent(String(p).split("?")[0]);
  } catch {
    clean = String(p).split("?")[0];
  }
  clean = clean.replace(/^\/+/, "") || "index.html";
  // Reject `..` segments AND any backslash: on Windows path.join treats `\` as a
  // separator, so a `..\` segment could otherwise escape the publish dir.
  if (clean.includes("\\")) return null;
  if (clean.split("/").some((seg) => seg === "..")) return null;
  return clean;
}

/**
 * Resolve a request path to the dist-relative file the host would serve,
 * mirroring Netlify semantics: an existing file wins (default shadowing), then
 * the matching redirect rule, then the SPA shell (index.html). Pure: the caller
 * supplies `fileExists(relPath)` so this stays unit-testable without IO.
 *
 * @param {string} reqPath request path, may include a leading slash and query
 * @param {{ from: string, to: string }[]} rules
 * @param {(relPath: string) => boolean} fileExists
 * @returns {string|null} dist-relative path, or null when nothing can be served
 */
export function resolveServePath(reqPath, rules, fileExists) {
  const direct = toServeRel(reqPath);
  if (direct && fileExists(direct)) return direct;

  const to = matchRedirect(reqPath, rules);
  if (to) {
    const target = toServeRel(to);
    if (target && fileExists(target)) return target;
  }
  return fileExists("index.html") ? "index.html" : null;
}
